import { MongoClient } from "mongodb";
import { config } from "../src/core/config.js";

const NOW = new Date().toISOString();

export const VERIFIED_PG_LISTINGS = [
  // ── KOLKATA PGs ──
  {
    title: "Zolo Stays - TechNest PG near RDB Boulevard & Godrej Waterside",
    source_platform: "Zolo",
    source_url: "https://example.com/zolo/technest-sector-v",
    property_type: "PG",
    rent: 8500,
    deposit: 8500,
    area_sqft: 140,
    furnishing: "furnished",
    images: ["/sample-room-1.jpg"],
    amenities: ["wifi", "meals", "daily housekeeping", "ac", "power backup", "cctv", "biometric entry"],
    location: { type: "Point", coordinates: [88.4342, 22.5758] }, // Exact RDB Boulevard / Sector V
    locality_id: "loc-sector-v",
    locality: "Sector V, Salt Lake",
    city: "Kolkata",
    nearby_metro: "Salt Lake Sector V Metro",
    commute_estimate_minutes: 5,
    dedupe_key: "pg-kolkata-sector5-zolo-technest",
    price_history: [
      { source: "Housing", rent: 8900, url: "https://example.com/housing/pg-sector-v-1", observed_at: NOW },
      { source: "MagicBricks", rent: 8500, url: "https://example.com/magicbricks/pg-sector-v-1", observed_at: NOW },
    ],
    is_active: true,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    title: "Stanza Living - Poznan House Co-Living near SDF Building & Webel More",
    source_platform: "Stanza Living",
    source_url: "https://example.com/stanza/poznan-house-sector-v",
    property_type: "co-living",
    rent: 9500,
    deposit: 9500,
    area_sqft: 160,
    furnishing: "furnished",
    images: ["/sample-room-2.jpg"],
    amenities: ["high-speed wifi", "chef-curated meals", "gym", "gaming zone", "laundry", "24/7 security"],
    location: { type: "Point", coordinates: [88.4318, 22.5735] }, // Exact SDF Building / Webel More
    locality_id: "loc-sector-v",
    locality: "Sector V, Salt Lake",
    city: "Kolkata",
    nearby_metro: "Salt Lake Sector V Metro",
    commute_estimate_minutes: 6,
    dedupe_key: "pg-kolkata-sector5-stanza-poznan",
    price_history: [
      { source: "Stanza", rent: 9500, url: "https://example.com/stanza/poznan", observed_at: NOW },
    ],
    is_active: true,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    title: "Executive AC PG near Wipro More & Candor TechSpace Gate 1",
    source_platform: "Housing",
    source_url: "https://example.com/housing/pg-wipro-more-sector-v",
    property_type: "PG",
    rent: 7500,
    deposit: 7500,
    area_sqft: 130,
    furnishing: "furnished",
    images: ["/sample-room-3.jpg"],
    amenities: ["wifi", "meals", "attached washroom", "power backup", "ro water", "refrigerator"],
    location: { type: "Point", coordinates: [88.4355, 22.5770] }, // Exact Wipro More
    locality_id: "loc-sector-v",
    locality: "Sector V, Salt Lake",
    city: "Kolkata",
    nearby_metro: "Salt Lake Sector V Metro",
    commute_estimate_minutes: 4,
    dedupe_key: "pg-kolkata-sector5-wipro-more-exec",
    price_history: [],
    is_active: true,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    title: "Your-Space Luxury PG near Globsyn Crystal & DLF 1",
    source_platform: "YourSpace",
    source_url: "https://example.com/yourspace/sector-v-crystal",
    property_type: "PG",
    rent: 10500,
    deposit: 10500,
    area_sqft: 180,
    furnishing: "furnished",
    images: ["/sample-room-1.jpg"],
    amenities: ["fiber wifi", "3 meals daily", "air conditioning", "housekeeping", "biometric access", "gym access"],
    location: { type: "Point", coordinates: [88.4368, 22.5742] }, // Exact Globsyn Crystal
    locality_id: "loc-sector-v",
    locality: "Sector V, Salt Lake",
    city: "Kolkata",
    nearby_metro: "Salt Lake Sector V Metro",
    commute_estimate_minutes: 5,
    dedupe_key: "pg-kolkata-sector5-yourspace-globsyn",
    price_history: [],
    is_active: true,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    title: "Millennium Professional PG near College More & Technopolis",
    source_platform: "MagicBricks",
    source_url: "https://example.com/magicbricks/pg-college-more",
    property_type: "PG",
    rent: 6500,
    deposit: 6500,
    area_sqft: 120,
    furnishing: "furnished",
    images: ["/sample-room-2.jpg"],
    amenities: ["wifi", "food available", "power backup", "washing machine", "geyser"],
    location: { type: "Point", coordinates: [88.4285, 22.5715] }, // Exact College More
    locality_id: "loc-sector-v",
    locality: "Sector V, Salt Lake",
    city: "Kolkata",
    nearby_metro: "Salt Lake Sector V Metro",
    commute_estimate_minutes: 8,
    dedupe_key: "pg-kolkata-sector5-college-more",
    price_history: [],
    is_active: true,
    created_at: NOW,
    updated_at: NOW,
  },

  // Salt Lake Sector 1, 2, 3
  {
    title: "Salt Lake Sector 2 AC PG for Techies near Karunamoyee Metro",
    source_platform: "Housing",
    source_url: "https://example.com/housing/pg-salt-lake-sec2",
    property_type: "PG",
    rent: 8000,
    deposit: 8000,
    area_sqft: 150,
    furnishing: "furnished",
    images: ["/sample-room-3.jpg"],
    amenities: ["metro walking distance", "wifi", "meals", "ac", "security", "geyser"],
    location: { type: "Point", coordinates: [88.4190, 22.5840] }, // Exact Karunamoyee / Sector 2
    locality_id: "loc-sector-2",
    locality: "Sector 2, Salt Lake",
    city: "Kolkata",
    nearby_metro: "Karunamoyee Metro",
    commute_estimate_minutes: 10,
    dedupe_key: "pg-kolkata-sec2-karunamoyee",
    price_history: [],
    is_active: true,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    title: "Homely PG near City Centre 1 & Central Park Metro",
    source_platform: "NoBroker",
    source_url: "https://example.com/nobroker/pg-city-centre-1",
    property_type: "PG",
    rent: 7000,
    deposit: 7000,
    area_sqft: 130,
    furnishing: "furnished",
    images: ["/sample-room-1.jpg"],
    amenities: ["wifi", "home cooked food", "quiet neighborhood", "ro water", "power backup"],
    location: { type: "Point", coordinates: [88.4085, 22.5930] }, // Exact City Centre 1 / Sector 1
    locality_id: "loc-sector-1",
    locality: "Sector 1, Salt Lake",
    city: "Kolkata",
    nearby_metro: "Central Park Metro",
    commute_estimate_minutes: 14,
    dedupe_key: "pg-kolkata-sec1-city-centre",
    price_history: [],
    is_active: true,
    created_at: NOW,
    updated_at: NOW,
  },

  // Kestopur / Tarulia Lane
  {
    title: "Tarulia Main Road AC PG with Food & WiFi (5 mins to Sector V)",
    source_platform: "Housing",
    source_url: "https://example.com/housing/pg-tarulia-lane",
    property_type: "PG",
    rent: 5500,
    deposit: 5500,
    area_sqft: 125,
    furnishing: "furnished",
    images: ["/sample-room-2.jpg"],
    amenities: ["wifi", "meals included", "attached bath", "washing machine", "inverter backup"],
    location: { type: "Point", coordinates: [88.4375, 22.5865] }, // Exact Tarulia Lane, Kestopur
    locality_id: "loc-kestopur",
    locality: "Tarulia Lane, Kestopur",
    city: "Kolkata",
    nearby_metro: "Salt Lake Sector V Metro",
    commute_estimate_minutes: 7,
    dedupe_key: "pg-kolkata-kestopur-tarulia",
    price_history: [],
    is_active: true,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    title: "Krishnapur Hanapara Boys & Girls PG near Footbridge",
    source_platform: "MagicBricks",
    source_url: "https://example.com/magicbricks/pg-hanapara-kestopur",
    property_type: "PG",
    rent: 4800,
    deposit: 4800,
    area_sqft: 110,
    furnishing: "furnished",
    images: ["/sample-room-3.jpg"],
    amenities: ["wifi", "food", "geyser", "refrigerator", "security"],
    location: { type: "Point", coordinates: [88.4330, 22.5910] }, // Exact Kestopur Hanapara
    locality_id: "loc-kestopur",
    locality: "Kestopur",
    city: "Kolkata",
    nearby_metro: "Salt Lake Sector V Metro",
    commute_estimate_minutes: 10,
    dedupe_key: "pg-kolkata-kestopur-hanapara",
    price_history: [],
    is_active: true,
    created_at: NOW,
    updated_at: NOW,
  },

  // New Town Action Area 1 & 2
  {
    title: "Stanza Living - Linz House PG near Ecospace & Axis Mall",
    source_platform: "Stanza Living",
    source_url: "https://example.com/stanza/linz-house-new-town",
    property_type: "co-living",
    rent: 8500,
    deposit: 8500,
    area_sqft: 150,
    furnishing: "furnished",
    images: ["/sample-room-1.jpg"],
    amenities: ["wifi", "meals", "housekeeping", "laundry", "gym", "security"],
    location: { type: "Point", coordinates: [88.4725, 22.5845] }, // Exact Action Area 1 / Axis Mall
    locality_id: "loc-new-town",
    locality: "Action Area 1, New Town",
    city: "Kolkata",
    nearby_metro: "Nazrul Tirtha Metro",
    commute_estimate_minutes: 12,
    dedupe_key: "pg-kolkata-newtown-stanza-linz",
    price_history: [],
    is_active: true,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    title: "Zolo Horizon Co-Living near Candor TechSpace Gate 1",
    source_platform: "Zolo",
    source_url: "https://example.com/zolo/horizon-new-town",
    property_type: "co-living",
    rent: 9000,
    deposit: 9000,
    area_sqft: 160,
    furnishing: "furnished",
    images: ["/sample-room-2.jpg"],
    amenities: ["wifi", "meals", "daily cleaning", "ac", "power backup", "cctv"],
    location: { type: "Point", coordinates: [88.4810, 22.5880] }, // Exact Candor TechSpace Gate 1
    locality_id: "loc-new-town",
    locality: "Action Area 1, New Town",
    city: "Kolkata",
    nearby_metro: "Candor Gate Metro",
    commute_estimate_minutes: 10,
    dedupe_key: "pg-kolkata-newtown-zolo-horizon",
    price_history: [],
    is_active: true,
    created_at: NOW,
    updated_at: NOW,
  },

  // ── BANGALORE PGs ──
  {
    title: "Zolo Amber Luxury PG near EcoSpace & Central Mall",
    source_platform: "Zolo",
    source_url: "https://example.com/zolo/amber-bellandur",
    property_type: "PG",
    rent: 9500,
    deposit: 9500,
    area_sqft: 150,
    furnishing: "furnished",
    images: ["/sample-room-1.jpg"],
    amenities: ["wifi", "meals", "ac", "housekeeping", "power backup", "biometric"],
    location: { type: "Point", coordinates: [77.6745, 12.9280] }, // Exact Bellandur EcoSpace
    locality_id: "loc-bellandur",
    locality: "Bellandur",
    city: "Bangalore",
    nearby_metro: "Bellandur Metro",
    commute_estimate_minutes: 5,
    dedupe_key: "pg-bangalore-bellandur-zolo-amber",
    price_history: [],
    is_active: true,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    title: "Stanza Living - Santa Clara House near Embassy TechVillage",
    source_platform: "Stanza Living",
    source_url: "https://example.com/stanza/santa-clara-bellandur",
    property_type: "co-living",
    rent: 11000,
    deposit: 11000,
    area_sqft: 170,
    furnishing: "furnished",
    images: ["/sample-room-2.jpg"],
    amenities: ["high-speed wifi", "chef meals", "gym", "gaming area", "laundry"],
    location: { type: "Point", coordinates: [77.6890, 12.9260] }, // Exact Embassy TechVillage / Devarabisanahalli
    locality_id: "loc-bellandur",
    locality: "Bellandur",
    city: "Bangalore",
    nearby_metro: "Kadubeesanahalli Metro",
    commute_estimate_minutes: 6,
    dedupe_key: "pg-bangalore-bellandur-stanza-santaclara",
    price_history: [],
    is_active: true,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    title: "Koramangala 4th Block Premium PG near Sony World Signal",
    source_platform: "Housing",
    source_url: "https://example.com/housing/pg-koramangala-4th-block",
    property_type: "PG",
    rent: 12000,
    deposit: 12000,
    area_sqft: 160,
    furnishing: "furnished",
    images: ["/sample-room-3.jpg"],
    amenities: ["wifi", "meals", "attached balcony", "ac", "security", "geyser"],
    location: { type: "Point", coordinates: [77.6275, 12.9335] }, // Exact Sony World Signal / 4th Block
    locality_id: "loc-koramangala",
    locality: "Koramangala",
    city: "Bangalore",
    nearby_metro: "Sony World Metro",
    commute_estimate_minutes: 8,
    dedupe_key: "pg-bangalore-koramangala-sonyworld",
    price_history: [],
    is_active: true,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    title: "HSR Sector 2 Tech PG near 27th Main Road & BDA Complex",
    source_platform: "NoBroker",
    source_url: "https://example.com/nobroker/pg-hsr-sec2",
    property_type: "PG",
    rent: 9000,
    deposit: 9000,
    area_sqft: 140,
    furnishing: "furnished",
    images: ["/sample-room-1.jpg"],
    amenities: ["wifi", "meals", "daily cleaning", "ro water", "power backup"],
    location: { type: "Point", coordinates: [77.6480, 12.9110] }, // Exact HSR 27th Main
    locality_id: "loc-hsr-layout",
    locality: "HSR Layout",
    city: "Bangalore",
    nearby_metro: "HSR Layout Metro",
    commute_estimate_minutes: 10,
    dedupe_key: "pg-bangalore-hsr-27thmain",
    price_history: [],
    is_active: true,
    created_at: NOW,
    updated_at: NOW,
  },

  // ── PUNE PGs ──
  {
    title: "Zolo Canvas Co-Living near Hinjawadi Phase 1 & Wipro Circle",
    source_platform: "Zolo",
    source_url: "https://example.com/zolo/canvas-hinjawadi-phase1",
    property_type: "co-living",
    rent: 7500,
    deposit: 7500,
    area_sqft: 150,
    furnishing: "furnished",
    images: ["/sample-room-2.jpg"],
    amenities: ["wifi", "meals", "housekeeping", "ac", "power backup", "cctv"],
    location: { type: "Point", coordinates: [73.7380, 18.5925] }, // Exact Hinjawadi Phase 1 / Wipro Circle
    locality_id: "loc-hinjawadi",
    locality: "Hinjawadi",
    city: "Pune",
    nearby_metro: "Megapolis Metro",
    commute_estimate_minutes: 5,
    dedupe_key: "pg-pune-hinjawadi-zolo-canvas",
    price_history: [],
    is_active: true,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    title: "Baner High Street Furnished PG near Balewadi High Street",
    source_platform: "Housing",
    source_url: "https://example.com/housing/pg-baner-high-street",
    property_type: "PG",
    rent: 9000,
    deposit: 9000,
    area_sqft: 160,
    furnishing: "furnished",
    images: ["/sample-room-3.jpg"],
    amenities: ["wifi", "meals", "attached bath", "balcony", "power backup", "security"],
    location: { type: "Point", coordinates: [73.7820, 18.5610] }, // Exact Baner High Street
    locality_id: "loc-baner",
    locality: "Baner",
    city: "Pune",
    nearby_metro: "Baner Metro",
    commute_estimate_minutes: 7,
    dedupe_key: "pg-pune-baner-high-street",
    price_history: [],
    is_active: true,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    title: "Dutt Mandir Road AC PG near Wakad Chowk & Hinjawadi Flyover",
    source_platform: "MagicBricks",
    source_url: "https://example.com/magicbricks/pg-wakad-dutt-mandir",
    property_type: "PG",
    rent: 7000,
    deposit: 7000,
    area_sqft: 135,
    furnishing: "furnished",
    images: ["/sample-room-1.jpg"],
    amenities: ["wifi", "food", "washing machine", "refrigerator", "power backup"],
    location: { type: "Point", coordinates: [73.7610, 18.5990] }, // Exact Wakad Dutt Mandir
    locality_id: "loc-wakad",
    locality: "Wakad",
    city: "Pune",
    nearby_metro: "Wakad Chowk Metro",
    commute_estimate_minutes: 8,
    dedupe_key: "pg-pune-wakad-duttmandir",
    price_history: [],
    is_active: true,
    created_at: NOW,
    updated_at: NOW,
  },

  // ── MUMBAI, HYDERABAD, NCR PGs ──
  {
    title: "BKC Kalanagar Executive PG near Diamond Bourse & MCA",
    source_platform: "NoBroker",
    source_url: "https://example.com/nobroker/pg-bkc-kalanagar",
    property_type: "PG",
    rent: 16000,
    deposit: 16000,
    area_sqft: 180,
    furnishing: "furnished",
    images: ["/sample-room-2.jpg"],
    amenities: ["ac", "wifi", "daily housekeeping", "meals", "24/7 security", "power backup"],
    location: { type: "Point", coordinates: [72.8580, 19.0640] }, // Exact BKC Kalanagar
    locality_id: "loc-bkc",
    locality: "Bandra Kurla Complex (BKC)",
    city: "Mumbai",
    nearby_metro: "BKC Metro",
    commute_estimate_minutes: 6,
    dedupe_key: "pg-mumbai-bkc-kalanagar",
    price_history: [],
    is_active: true,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    title: "HITEC City Cyber Towers PG near Mindspace IT Park & Metro",
    source_platform: "Zolo",
    source_url: "https://example.com/zolo/cyber-towers-hitec-city",
    property_type: "PG",
    rent: 8500,
    deposit: 8500,
    area_sqft: 150,
    furnishing: "furnished",
    images: ["/sample-room-3.jpg"],
    amenities: ["wifi", "meals", "ac", "security", "housekeeping", "power backup"],
    location: { type: "Point", coordinates: [78.3810, 17.4480] }, // Exact Cyber Towers / HITEC City
    locality_id: "loc-hitec-city",
    locality: "HITEC City",
    city: "Hyderabad",
    nearby_metro: "HITEC City Metro",
    commute_estimate_minutes: 5,
    dedupe_key: "pg-hyderabad-hitec-cybertowers",
    price_history: [],
    is_active: true,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    title: "DLF Cyber City Phase 2 Executive PG near IndusInd Bank Metro",
    source_platform: "Housing",
    source_url: "https://example.com/housing/pg-cyber-city-phase2",
    property_type: "PG",
    rent: 12500,
    deposit: 12500,
    area_sqft: 170,
    furnishing: "furnished",
    images: ["/sample-room-1.jpg"],
    amenities: ["ac", "wifi", "meals", "attached bath", "elevator", "power backup"],
    location: { type: "Point", coordinates: [77.0865, 28.4940] }, // Exact DLF Cyber City Phase 2
    locality_id: "loc-cyber-city",
    locality: "DLF Cyber City",
    city: "Delhi NCR",
    nearby_metro: "Cyber City Rapid Metro",
    commute_estimate_minutes: 5,
    dedupe_key: "pg-delhi-cybercity-phase2",
    price_history: [],
    is_active: true,
    created_at: NOW,
    updated_at: NOW,
  },
];

async function seedVerifiedPGs() {
  const client = new MongoClient(config.MONGODB_URI);
  try {
    await client.connect();
    const db = client.db(config.MONGODB_DB);

    console.log("Seeding high-precision verified PG listings into MongoDB...");

    // Upsert into unified collection 'properties'
    for (const pg of VERIFIED_PG_LISTINGS) {
      await db.collection("properties").updateOne(
        { dedupe_key: pg.dedupe_key },
        { $set: pg },
        { upsert: true }
      );

      // Also upsert into city partitioned collections
      const cleanCity = pg.city.toLowerCase().trim();
      const citySlug = cleanCity === "bengaluru" ? "bangalore" : cleanCity;
      const partitionName = `properties_${citySlug.replace(/\s+/g, "_")}`;

      await db.collection(partitionName).updateOne(
        { dedupe_key: pg.dedupe_key },
        { $set: pg },
        { upsert: true }
      );
    }

    console.log(`Successfully seeded ${VERIFIED_PG_LISTINGS.length} verified PG listings with exact building coordinates!`);
  } finally {
    await client.close();
  }
}

seedVerifiedPGs().catch((err) => {
  console.error("Seeding PGs failed:", err);
  process.exit(1);
});
